### PR TITLE
implements new navigation design and removes stories

### LINKED ISSUE #979: implement navigation design tweaks and remove stories

### PR DESCRIPTION
**Pull request by davelandry**
- removes stories (#979)
 - renames "profiles" to "reports" in front-end texts (#979)
 - implements Danae's new navigation design (#979)
 - adds profile colors to home splash tiles
 - adds COVID stripe in homepage

Screen Shot 2022-07-21 at 10 26 47 AM

Screen Shot 2022-07-21 at 10 27 58 AM

Screen Shot 2022-07-21 at 10 30 26 AM

Closes #979

### CODE REVIEW

**Comment by hermosillajelmy** [comment]
@davelandry I am losing the cart when I shrink the screen and I think it is useful keep the quick access 
Captura de Pantalla 2022-07-26 a la(s) 17 01 25

**Comment by davelandry** [comment]
@hermosillajelmy good feedback, I wasn't sure what to hide/show there. I've made the following tweaks:
 - Cart icon is always visible
 - Page titles (like when on profiles or cart itself) are now left-aligned
 - If the page has no custom "red" title, the DataUSA logo will appear (previously there was nothing on mobile)

Screen Shot 2022-07-27 at 10 09 46 AM

**Comment by hermosillajelmy** [comment]
@davelandry I like it! but I found other sections a bit broken in home for mobile version
Captura de Pantalla 2022-07-27 a la(s) 11 12 42 11 12 19](https://user-images.githubusercontent.com/59574973/181284162-cdc76959-bb58-4cb6-bd36-b57de896a01e.png)
-4202-82fa-87535
Captura de Pantalla 2022-07-27 a la(s) 11 12 02
d752769.png)

**Comment by davelandry** [comment]
I'd like to save the mobile fixes related to #983 for a separate PR, if that's alright with you @hermosillajelmy 🙏🏻

**Pull request merged**
