### PR TITLE
new profile and viz color styles

### LINKED ISSUE #978: implement new profile design tweaks

### PR DESCRIPTION
**Pull request by davelandry**
* implements Danae's profile design tweaks
* uploads new icons for Transportation Means
* updates Colors JSON with all/new values
* passes color mapping in customAttributes
* hides certain Splash stats in geo profile in comparison mode

Closes #978

### CODE REVIEW

**Comment by hermosillajelmy** [comment]
@davelandry the dots on the right are not working quite right, a section that does not exist in that profile appears as selected and if I go down the site it does not change, being that they should mark the section that I am seeing. I'm reviewing the USA profile.

https://user-images.githubusercontent.com/59574973/184434130-d3b2e0d3-b077-4a41-a364-85b3a4c6042f.mov

**Comment by hermosillajelmy** [comment]
broken viz in education section -> concentrations (nation profile)

Captura de Pantalla 2022-08-12 a la(s) 15 47 50

**Comment by hermosillajelmy** [comment]
the subtitle does not work in all profiles

Captura de Pantalla 2022-08-12 a la(s) 16 43 07

**Comment by hermosillajelmy** [comment]
some icons are missing (http://localhost:3300/profile/soc/management-business-science-arts-occupations)

Captura de Pantalla 2022-08-12 a la(s) 17 33 36

**Comment by hermosillajelmy** [comment]
broken viz (http://localhost:3300/profile/university/doctoral-universities#rate)
Captura de Pantalla 2022-08-12 a la(s) 17 53 18

**Comment by davelandry** [comment]
@hermosillajelmy I have just pushed some code (along with a few CMS tweaks) to fix all of these bugs. Great find! Most of them were related to a few missing and duplicate colors.

I have also updated all of the minor d3plus dependencies, which brings a lot of small bug fixes (like those weird "hover elements stay hovered" bugs we were hunting down a few months ago).

Ready for your re-review!

**Pull request merged**
