### PR TITLE
replaces Profile SubNav/SideNav with the canon-cms Subnav component

### LINKED ISSUE #997: remove old profile groupings and use new SubGrouping with Nav

### PR DESCRIPTION
**Pull request by davelandry**
Screen Shot 2022-10-13 at 3 27 51 PM

 - updates to latest canon-core and canon-cms 
 - replaces Profile SubNav and SideNav with the canon-cms Subnav component 
 - adds Icon support to Section titles 
 - removes old Splash section icons and improves height logic 
 - creates SubGrouping section to enable Subnav dropdowns
 - adjusts padding on nav logo to better align with page titles

Closes #997

### CODE REVIEW

**Comment by hermosillajelmy** [comment]
@davelandry the & is not working properly in the subnav

Captura de Pantalla 2022-11-02 a la(s) 12 35 29

**Comment by hermosillajelmy** [comment]
is it possible to add the subnav in the mobile version? I find it very useful

Captura de Pantalla 2022-11-02 a la(s) 12 56 47

**Comment by hermosillajelmy** [comment]
on small screens I can only see the sections that belong to a group when I click the title and only for a moment because it redirects me to the group where I clicked

https://user-images.githubusercontent.com/59574973/199541351-cc6e2e3e-4917-4f39-b3d4-5cd0a1236c52.mov

**Comment by davelandry** [comment]
@hermosillajelmy regarding the tablet/mobile behavior: since this is new SubNav is a canon-cms component, I would like to defer those ideas as improvements to the core component and not hold up this PR (we have other sites, like DataMexico, which have this same problem 😅)

Regarding the ampersands... I can't recreate your bug! They look fine for me in Chrome and Firefox:
Screen Shot 2022-11-09 at 6 26 33 PM

**Pull request merged**
